# Loki Configuration
# Log aggregation and storage with AWS S3 + DynamoDB integration

# Global settings
nameOverride: "loki"
fullnameOverride: "loki"

# Loki configuration
loki:
  # Enable structured configuration
  structuredConfig:
    # Authentication and tenant configuration
    auth_enabled: false # Single tenant mode for simplicity

    # Server configuration
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095
      grpc_server_max_recv_msg_size: 104857600 # 100MB
      grpc_server_max_send_msg_size: 104857600 # 100MB

    # Common configuration
    common:
      path_prefix: /var/loki
      storage:
        s3:
          endpoint: ""
          region: us-west-2
          bucketnames: "observability-loki-logs" # Override with Terraform output
          sse_encryption: true
          sse:
            type: SSE-KMS
            kms_key_id: "" # Populate with Terraform KMS key ID
      ring:
        kvstore:
          store: memberlist
        instance_addr: 127.0.0.1

    # Memberlist configuration for clustering
    memberlist:
      join_members:
        - loki-memberlist

    # Schema configuration for S3 + DynamoDB
    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h

    # Storage configuration
    storage_config:
      # S3 configuration for chunks
      aws:
        s3: "observability-loki-logs" # Override with Terraform output
        region: us-west-2
        sse_encryption: true
        kms_key_id: "" # Populate with Terraform KMS key ID

      # DynamoDB configuration for index
      dynamodb:
        dynamodb_url: "dynamodb://us-west-2"

      # TSDB shipper configuration
      tsdb_shipper:
        active_index_directory: /var/loki/index
        cache_location: /var/loki/index_cache
        shared_store: s3

    # Limits configuration
    limits_config:
      # Ingestion limits
      ingestion_rate_mb: 50
      ingestion_burst_size_mb: 100
      max_global_streams_per_user: 10000
      max_query_parallelism: 32

      # Query limits
      max_query_length: 721h # 30 days
      max_query_series: 100000
      max_streams_matchers_per_query: 1000

      # Retention (7 years like Mimir)
      retention_period: 2555d

# Deployment mode - use simple scalable mode
deploymentMode: SimpleScalable

# Backend configuration
backend:
  replicas: 3
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "gp3"
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi

# Read component configuration
read:
  replicas: 3
  persistence:
    enabled: true
    size: 20Gi
    storageClass: "gp3"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Write component configuration
write:
  replicas: 3
  persistence:
    enabled: true
    size: 50Gi
    storageClass: "gp3"
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

# Gateway configuration
gateway:
  enabled: true
  replicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Service account with IRSA
serviceAccount:
  create: true
  name: loki
  annotations:
    eks.amazonaws.com/role-arn: "" # Populate with Terraform IRSA role ARN

# Monitoring configuration
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      app.kubernetes.io/part-of: observability-stack
    interval: 30s
    scrapeTimeout: 10s

# Disable single binary mode (using SimpleScalable)
singleBinary:
  replicas: 0
