groups:
  - name: infrastructure-alerts
    orgId: 1
    folder: Infrastructure
    interval: 1m
    rules:
      - uid: node-cpu-high
        title: High CPU Usage
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: __expr__
              uid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [80]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              reducer: last
              settings:
                mode: ""
              type: reduce
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "CPU usage is above 80% for more than 5 minutes"
          summary: "High CPU usage detected"
        labels:
          severity: warning

  - name: application-alerts
    orgId: 1
    folder: Applications
    interval: 1m
    rules:
      - uid: app-error-rate-high
        title: High Error Rate
        condition: C
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
          - refId: C
            queryType: ""
            relativeTimeRange:
              from: 0
              to: 0
            datasource:
              type: __expr__
              uid: __expr__
            model:
              conditions:
                - evaluator:
                    params: [5]
                    type: gt
                  operator:
                    type: and
                  query:
                    params: [A]
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              reducer: last
              settings:
                mode: ""
              type: reduce
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "Application error rate is above 5% for more than 2 minutes"
          summary: "High application error rate detected"
        labels:
          severity: critical
