apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack-alerts
    receivers:
      - uid: slack001
        type: slack
        settings:
          url: ${SLACK_WEBHOOK_URL}
          channel: "#observability-alerts"
          title: "Grafana Alert"
          text: |
            {{ range .Alerts }}
            Alert: {{ .Annotations.summary }}
            Description: {{ .Annotations.description }}
            {{ end }}

  - orgId: 1
    name: email-alerts
    receivers:
      - uid: email001
        type: email
        settings:
          addresses: ${ALERT_EMAIL_ADDRESSES}
          subject: "Grafana Alert: {{ .GroupLabels.alertname }}"

policies:
  - orgId: 1
    receiver: slack-alerts
    group_by: ["alertname", "cluster", "service"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    routes:
      - receiver: email-alerts
        matchers:
          - severity = critical
        group_wait: 10s
        repeat_interval: 5m
