apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: https://github.com/NaserRaoofi/observability-platform.git
    targetRevision: main
    path: k8s/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  revisionHistoryLimit: 20
  info:
    - name: "Environment"
      value: "Production"
    - name: "Contact"
      value: "Platform Team"
    - name: "Approval"
      value: "Manual sync with approval required"
    - name: "Maintenance Window"
      value: "Sunday 02:00-04:00 UTC"
