apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: https://github.com/NaserRaoofi/observability-platform.git
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Environment"
      value: "Staging"
    - name: "Contact"
      value: "DevOps Team"
    - name: "Approval"
      value: "Manual sync required"
