apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  source:
    repoURL: https://github.com/NaserRaoofi/observability-platform.git
    targetRevision: developer
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Environment"
      value: "Development"
    - name: "Contact"
      value: "DevOps Team"
