apiVersion: 1

folders:
  - title: SRE
    uid: sre-folder
    orgId: 1

  - title: Applications
    uid: app-folder
    orgId: 1

  - title: Infrastructure
    uid: infra-folder
    orgId: 1

  - title: SLO
    uid: slo-folder
    orgId: 1
