apiVersion: v1
kind: Deployment
metadata:
  name: demo-shop
  namespace: default
  labels:
    app: demo-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-shop
  template:
    metadata:
      labels:
        app: demo-shop
    spec:
      serviceAccountName: demo-shop-sa
      containers:
        - name: demo-shop
          image: demo-shop:latest
          ports:
            - containerPort: 8000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4317"
            - name: OTEL_SERVICE_NAME
              value: "demo-shop"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=demo-shop,service.version=1.0.0"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: demo-shop
  labels:
    app: demo-shop
spec:
  selector:
    app: demo-shop
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-shop-sa
  namespace: default
