#!/bin/bash
set -euo pipefail

# GitOps Image Update Script
# Updates container image tags in GitOps configurations

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GITOPS_DIR="${SCRIPT_DIR}"

# Input parameters
IMAGE_TAG="${1:-latest}"
ENVIRONMENT="${2:-dev}"
IMAGE_DIGEST="${3:-}"
SOURCE_COMMIT="${4:-}"

echo "🚀 GitOps Image Update"
echo "====================="
echo "Environment: ${ENVIRONMENT}"
echo "Image Tag: ${IMAGE_TAG}"
echo "Image Digest: ${IMAGE_DIGEST}"
echo "Source Commit: ${SOURCE_COMMIT}"

# Function to update image tag in Kustomization files
update_kustomization() {
    local env_path="$1"
    local new_tag="$2"

    if [[ -f "${env_path}/kustomization.yaml" ]]; then
        echo "📝 Updating kustomization.yaml in ${env_path}"

        # Update image tag using yq if available, otherwise use sed
        if command -v yq >/dev/null 2>&1; then
            yq eval ".images[0].newTag = \"${new_tag}\"" -i "${env_path}/kustomization.yaml"
        else
            # Fallback to sed for basic tag replacement
            sed -i "s/newTag: .*/newTag: ${new_tag}/" "${env_path}/kustomization.yaml"
        fi

        echo "✅ Updated image tag to: ${new_tag}"
    else
        echo "⚠️ No kustomization.yaml found in ${env_path}"
    fi
}

# Function to create or update image tracking file
update_image_tracking() {
    local env_dir="$1"
    local image_info="$2"

    mkdir -p "${env_dir}"

    cat > "${env_dir}/image-info.yaml" << EOF
# Auto-generated by GitOps CI pipeline
# Last updated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

apiVersion: v1
kind: ConfigMap
metadata:
  name: image-tracking
  namespace: observability-${ENVIRONMENT}
data:
  image-tag: "${IMAGE_TAG}"
  image-digest: "${IMAGE_DIGEST}"
  source-commit: "${SOURCE_COMMIT}"
  updated-at: "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  updated-by: "ci-pipeline"
  environment: "${ENVIRONMENT}"
EOF

    echo "📋 Created image tracking info"
}

# Main update logic based on environment and branch
case "${ENVIRONMENT}" in
    "dev")
        echo "🧪 Updating development environment"
        ENV_PATH="${GITOPS_DIR}/environments/dev"
        K8S_PATH="../k8s/overlays/dev"

        # Development gets latest tags from developer branch
        if [[ "${IMAGE_TAG}" == "latest" || "${IMAGE_TAG}" =~ ^sha-.* ]]; then
            update_kustomization "${K8S_PATH}" "${IMAGE_TAG}"
            update_image_tracking "${ENV_PATH}" "${IMAGE_TAG}"
        else
            echo "ℹ️ Non-latest tag ${IMAGE_TAG} not applied to dev environment"
        fi
        ;;

    "staging")
        echo "🏗️ Updating staging environment"
        ENV_PATH="${GITOPS_DIR}/environments/staging"
        K8S_PATH="../k8s/overlays/staging"

        # Staging gets semantic version tags only
        if [[ "${IMAGE_TAG}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            update_kustomization "${K8S_PATH}" "${IMAGE_TAG}"
            update_image_tracking "${ENV_PATH}" "${IMAGE_TAG}"

            echo "📢 Staging update requires manual ArgoCD sync"
        else
            echo "ℹ️ Non-semantic version tag ${IMAGE_TAG} not applied to staging"
        fi
        ;;

    "prod")
        echo "🚀 Production environment update"
        ENV_PATH="${GITOPS_DIR}/environments/prod"
        K8S_PATH="../k8s/overlays/prod"

        # Production only gets stable semantic versions (manual process)
        echo "⚠️ Production updates require manual approval process"
        echo "📋 Candidate image: ${IMAGE_TAG}"
        echo "📋 Use 'promote-to-production.sh ${IMAGE_TAG}' after approval"

        # Create promotion candidate file
        update_image_tracking "${ENV_PATH}" "${IMAGE_TAG}"
        ;;

    *)
        echo "❌ Unknown environment: ${ENVIRONMENT}"
        echo "Valid environments: dev, staging, prod"
        exit 1
        ;;
esac

# Create commit if there are changes
if git diff --quiet; then
    echo "ℹ️ No changes to commit"
else
    echo "📝 Committing GitOps changes"
    git add .
    git commit -m "GitOps: Update ${ENVIRONMENT} to ${IMAGE_TAG}

- Environment: ${ENVIRONMENT}
- Image Tag: ${IMAGE_TAG}
- Image Digest: ${IMAGE_DIGEST}
- Source Commit: ${SOURCE_COMMIT}
- Updated by: CI Pipeline"

    echo "✅ GitOps update completed"
    echo "🔄 ArgoCD will detect and sync changes"
fi

echo ""
echo "📊 GitOps Update Summary:"
echo "========================"
echo "✅ Environment: ${ENVIRONMENT}"
echo "✅ Image Tag: ${IMAGE_TAG}"
echo "📁 Updated Path: ${K8S_PATH}"
echo "🔄 Next: ArgoCD sync (automatic for dev, manual for staging/prod)"
