apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress-chaos
  namespace: observability
  labels:
    app: chaos-cpu-stress
spec:
  containers:
    - name: stress
      image: progrium/stress:latest
      command: ["stress"]
      args: ["--cpu", "2", "--timeout", "300s"]
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 2000m
          memory: 256Mi
  restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-stress-job
  namespace: observability
spec:
  template:
    spec:
      containers:
        - name: stress
          image: progrium/stress:latest
          command: ["stress"]
          args: ["--cpu", "1", "--timeout", "60s"]
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 256Mi
      restartPolicy: Never
  backoffLimit: 1
