apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: observability-base
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: observability

resources:
  # 1. Security policies first (creates namespace and security constraints)
  - policy/

  # 2. Storage and data components
  - mimir/
  - loki/
  - tempo/

  # 3. Collection layer
  - otel-collector/
  - exporters/

  # 4. SLO monitoring
  - sloth/

  # 5. Alerting
  - alertmanager/

  # 6. Visualization (last, depends on data sources being ready)
  - grafana/

labels:
  - pairs:
      app.kubernetes.io/part-of: observability-stack
      app.kubernetes.io/managed-by: kustomize
      environment: base

commonAnnotations:
  app.kubernetes.io/version: "v1.0.0"
  config.k8s.io/origin: |
    configuredIn: k8s/base/kustomization.yaml
    configuredBy: kustomize
  # Platform metadata
  observability.platform/deployment-date: "2025-11-01"
  observability.platform/config-hash: "base-v1.0.0"

# Apply consistent labeling across all components
commonLabels:
  observability.platform/stack: "enterprise"
  observability.platform/version: "v1.0.0"

# Component deployment order
# 1. Security policies first
# 2. Storage and data components (Mimir, Loki, Tempo)
# 3. Collection layer (OTel Collector, exporters)
# 4. SLO monitoring (Sloth)
# 5. Alerting (AlertManager)
# 6. Visualization (Grafana)

# Image transformations (can be used to override image versions globally)
images: []

# Strategic merge patches (for complex patches)
patchesStrategicMerge: []

# JSON 6902 patches (for targeted patches)
patches: []

# Replacement transformations
replacements: []

# Configuration generators (for dynamic config generation)
configMapGenerator: []
secretGenerator: []

# Resource generation options
generatorOptions:
  disableNameSuffixHash: false
  labels:
    app.kubernetes.io/managed-by: kustomize
  annotations:
    config.kubernetes.io/origin: "k8s/base/kustomization.yaml"
